version: "3.5"

services:
  server:
    image: web-project/nest
    container_name: nest
    depends_on:
      - db
    expose:
      - "8095"
    ports:
      - "8095:3000"
    environment:
      - DB_URL=mongodb://db_mongo
      - SEND_PULSE_API_USER_ID=${SEND_PULSE_API_SECRET}
      - SEND_PULSE_API_SECRET=${SEND_PULSE_API_SECRET}
      - SEND_PULSE_TOKEN_STORAGE=${SEND_PULSE_TOKEN_STORAGE}
      - OTAKE_EMAIL=${OTAKE_EMAIL}
      - OTAKE_NAME=${OTAKE_NAME}

  client:
    image: web-project/client
    container_name: react
    expose:
      - "8096"
    ports:
      - "8096:4200"

  db:
    image: mongo:latest
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodata:
