/* Generated by restful-react */

import React from "react";
import { Get, GetProps, useGet, UseGetProps, Mutate, MutateProps, useMutate, UseMutateProps } from "restful-react";
export const SPEC_VERSION = "1.0";
// tslint:disable-next-line:no-empty-interface
export interface ContactInput { }

export type AppControllerGetHelloProps = Omit<GetProps<void, unknown, void, void>, "path">;

export const AppControllerGetHello = (props: AppControllerGetHelloProps) => (
  <Get<void, unknown, void, void>
    path={`/api/v0`}

    {...props}
  />
);

export type UseAppControllerGetHelloProps = Omit<UseGetProps<void, unknown, void, void>, "path">;

export const useAppControllerGetHello = (props: UseAppControllerGetHelloProps) => useGet<void, unknown, void, void>(`/api/v0`, props);


export type IncidencesControllerGetIncidencesProps = Omit<GetProps<void, unknown, void, void>, "path">;

export const IncidencesControllerGetIncidences = (props: IncidencesControllerGetIncidencesProps) => (
  <Get<void, unknown, void, void>
    path={`/api/v0/incidences`}

    {...props}
  />
);

export type UseIncidencesControllerGetIncidencesProps = Omit<UseGetProps<void, unknown, void, void>, "path">;

export const useIncidencesControllerGetIncidences = (props: UseIncidencesControllerGetIncidencesProps) => useGet<void, unknown, void, void>(`/api/v0/incidences`, props);


export type IncidencesControllerUploadFileProps = Omit<MutateProps<void, unknown, void, void, void>, "path" | "verb">;

export const IncidencesControllerUploadFile = (props: IncidencesControllerUploadFileProps) => (
  <Mutate<void, unknown, void, void, void>
    verb="POST"
    path={`/api/v0/incidences`}

    {...props}
  />
);

export type UseIncidencesControllerUploadFileProps = Omit<UseMutateProps<void, unknown, void, void, void>, "path" | "verb">;

export const useIncidencesControllerUploadFile = (props: UseIncidencesControllerUploadFileProps) => useMutate<void, unknown, void, void, void>("POST", `/api/v0/incidences`, props);


export type IncidencesControllerGetIncidencesByRegionProps = Omit<GetProps<void, unknown, void, void>, "path">;

export const IncidencesControllerGetIncidencesByRegion = (props: IncidencesControllerGetIncidencesByRegionProps) => (
  <Get<void, unknown, void, void>
    path={`/api/v0/incidences/regions`}

    {...props}
  />
);

export type UseIncidencesControllerGetIncidencesByRegionProps = Omit<UseGetProps<void, unknown, void, void>, "path">;

export const useIncidencesControllerGetIncidencesByRegion = (props: UseIncidencesControllerGetIncidencesByRegionProps) => useGet<void, unknown, void, void>(`/api/v0/incidences/regions`, props);


export type FiltersControllerGetClassAgesProps = Omit<GetProps<void, unknown, void, void>, "path">;

export const FiltersControllerGetClassAges = (props: FiltersControllerGetClassAgesProps) => (
  <Get<void, unknown, void, void>
    path={`/api/v0/incidences/filters/class-age`}

    {...props}
  />
);

export type UseFiltersControllerGetClassAgesProps = Omit<UseGetProps<void, unknown, void, void>, "path">;

export const useFiltersControllerGetClassAges = (props: UseFiltersControllerGetClassAgesProps) => useGet<void, unknown, void, void>(`/api/v0/incidences/filters/class-age`, props);


export type CaseConfirmControllerGetCaseConfirmProps = Omit<GetProps<void, unknown, void, void>, "path">;

export const CaseConfirmControllerGetCaseConfirm = (props: CaseConfirmControllerGetCaseConfirmProps) => (
  <Get<void, unknown, void, void>
    path={`/api/v0/case-confirm`}

    {...props}
  />
);

export type UseCaseConfirmControllerGetCaseConfirmProps = Omit<UseGetProps<void, unknown, void, void>, "path">;

export const useCaseConfirmControllerGetCaseConfirm = (props: UseCaseConfirmControllerGetCaseConfirmProps) => useGet<void, unknown, void, void>(`/api/v0/case-confirm`, props);


export type ContactControllerContactProps = Omit<MutateProps<void, unknown, void, ContactInput, void>, "path" | "verb">;

export const ContactControllerContact = (props: ContactControllerContactProps) => (
  <Mutate<void, unknown, void, ContactInput, void>
    verb="POST"
    path={`/api/v0/contact`}

    {...props}
  />
);

export type UseContactControllerContactProps = Omit<UseMutateProps<void, unknown, void, ContactInput, void>, "path" | "verb">;

export const useContactControllerContact = (props: UseContactControllerContactProps) => useMutate<void, unknown, void, ContactInput, void>("POST", `/api/v0/contact`, props);
