export const mapIdToRegion = {
  '00': 'Toutes',
  11: 'Île-de-France',
  '01': 'Guadeloupe',
  '02': 'Martinique',
  '03': 'Guyane',
  '04': 'Réunion',
  '06': 'Mayotte',
  24: 'Centre-Val de Loire',
  27: 'Bourgogne et Franche-Comté',
  28: 'Normandie',
  32: 'Hauts-de-France',
  44: 'Grand Est',
  52: 'Pays de la Loire',
  53: 'Bretagne',
  75: 'Nouvelle Aquitaine',
  76: 'Occitanie',
  84: 'Auvergne et Rhône-Alpes',
  93: 'Provence-Alpes-Côte d\'Azur',
  94: 'Corse',
  975: 'Miquelon-Langlade et Saint Pierre',
  977: 'Saint-Barthélemy',
  978: 'Saint-Martin',
};
