export const mapNameRegionToCode = {
  'Île-de-France': 11,
  Guadeloupe: '01',
  Martinique: '02',
  Guyane: '03',
  Réunion: '04',
  Mayotte: '06',
  'Centre-Val de Loire': 24,
  'Bourgogne et Franche-Comté': 27,
  Normandie: 28,
  'Hauts-de-France': 32,
  'Grand Est': 44,
  'Pays de la Loire': 52,
  Bretagne: 53,
  'Nouvelle Aquitaine': 75,
  Occitanie: 76,
  'Auvergne et Rhône-Alpes': 84,
  'Provence-Alpes-Côte d\'Azur': 93,
  Corse: 94,
  'Miquelon-Langlade et Saint Pierre': 975,
  'Saint-Barthélemy': 977,
  'Saint-Martin': 978,
};
